# Mirrors the GitHub `cargo-deny` job (license / advisory / ban checks).
when:
  - event: pull_request
  - event: push
    branch: [main, master]

steps:
  - name: cargo-deny
    image: rust:bookworm
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - cargo install cargo-deny --locked
      - cargo deny check
